from __future__ import annotations
from typing import Any, Dict, Union, List, Tuple, AnyStr, Optional, TypeVar


class BaseMockRequest:
    """
    dual-purpose class used to represent:
    - Actual Requests when created from parameters of @actual_request
    - Expected Requests when created from parameters of @mock_server
    (or similar factory)

    these are stored in store fixture, indexed by: test name, factory name(s), then BaseMockRequest
    object
    """

    FACTORY_NAME = 'make_factory'
    FACTORY_PATH = 'pytest_factory.framework.factory'

    def compare(self, other) -> bool:
        """
        we are effectively simulating the third-party endpoint's router here. note that "this" is the request object of
        the test double that MAY match actual. the "other" request object is the actual request generated by the
        component under test
        e.g. "https://www.test.com?id=0&loc=1" should match
        "https://www.test.com?loc=1&id=0"
        """
        raise NotImplementedError


def compare_unknown_types(a, b) -> bool:
    if hasattr(a, 'compare'):
        compare_result = a.compare(b)
    elif hasattr(b, 'compare'):
        compare_result = b.compare(a)
    else:
        compare_result = a == b
    return compare_result


class Factory(dict):
    def __init__(self, req_obj: Union[str, BaseMockRequest], responses: Any):
        super().__init__()
        self.__setitem__(req_obj, responses)

    def __setitem__(self, key, value):
        for _key in self.keys():
            if compare_unknown_types(key, _key):
                return
        super().__setitem__(key, value)

    @property
    def FACTORY_NAME(self):
        return list(self.keys())[0]


class BasePlugin:
    """
    to create a pytest-factory plugin, inherit from this base class and define the following:
    - self.PLUGIN_URL
    - self.get_plugin_responses

    PLUGIN_URL is the url that corresponds to the depended-on-component that this plugin simulates
    """
    # TODO seems unnecessary to make this a class - rework to replace with module
    PLUGIN_URL = None

    def __init__(self):
        if self.PLUGIN_URL is None:
            raise NotImplementedError()

    @staticmethod
    def get_plugin_responses(req_obj: BaseMockRequest) -> Any:
        """
        this method will be called by Store.get_next_response when the system-under-test calls a url matching
        self.PLUGIN_URL. the user-defined plugin should override this method to implement a router that returns
        the plugin-defined test double response
        """
        raise NotImplementedError


ROUTING_TYPE = Dict[
    Union[
        Dict[str, Any],
        BaseMockRequest],
    Any
]
T = TypeVar("T")

MAGIC_TYPE = Optional[Union[List[T], T]]
BASE_RESPONSE_TYPE = Union[Exception, object, AnyStr]
MOCK_RESPONSES_TYPE = List[Tuple[bool, BASE_RESPONSE_TYPE]]
