import pytest

from json import JSONDecodeError 


from pytest_factory import mock_request

from tests.passthru_app import PassthruTestHandler


pytestmark = pytest.mark.asyncio

sut_inputs = {'body': '<xmlDoc>foo</xmlDoc>', 'method': 'post', 'path': '/'}



class TestPassthruTestHandlerJSONDecodeError:
    """
    TestPassthruTestHandlerJSONDecodeError was generated by PytestFactory

    """
    
    @mock_request(**sut_inputs, handler_class=PassthruTestHandler)
    async def test_example_0(self, store):
        
        with pytest.raises(JSONDecodeError):
            await store.handler.run_test()
        